postgresql:
  postgresqlPassword: password
  postgresqlDatabase: address
  service.type: ClusterIP

projeto-viacep-backend:
  replicaCount: 1

  image:
    repository: hudsonfranca/projeto-viacep-backend
    tag: "k8s"

  resources:
    limits:
      cpu: "0.5"
      memory: "270Mi"
    requests:
      cpu: "0.5"
      memory: "270Mi"

  database:
    user: postgres
    ## O host é formado pelo nome do Release e "-postgresql"
    ## ex: se o Release name for "projeto-viacep", o host vai ser: projeto-viacep-postgresql 
    host: projeto-viacep-postgresql 
    port: 5432
    database: address
    ## password deve ser no formato base64
    password: cGFzc3dvcmQ=


projeto-viacep-frontend:

  replicaCount: 1

  image:
    repository: hudsonfranca/projeto-viacep-frontend
    tag: "k8s"

  resources:
    limits:
      cpu: "0.5"
      memory: "270Mi"
    requests:
      cpu: "0.5"
      memory: "270Mi"



